services:
  calculation-bot:
    image: ghcr.io/bexull/report_bot:master
    container_name: calculation-bot
    restart: unless-stopped
    network_mode: host
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"